In [3]:
import numpy as np

In [45]:
H = 8
W= 8
cx = 5
cy = 5
r = 3
y, x = np.ogrid[:H, :W]
"""Boolean mask for a circle centered at (cx, cy)."""
foo = (x - cx)**2 + (y - cy)**2 < r**2
foo

array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True],
       [False, False, False,  True,  True,  True,  True,  True]])

In [46]:
foo.sum()

np.int64(25)

In [39]:
bar = np.zeros((1,5,8,8))
x = np.array([1,2,3,4,5])
bar[:, :, foo] = x[None, :, None]
bar

array([[[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1., 1., 1., 1.],
         [0., 0., 0., 1., 1., 1., 1., 1.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 2., 2., 2., 2., 2.],
         [0., 0., 0., 2., 2., 2., 2., 2.],
         [0., 0., 0., 2., 2., 2., 2., 2.],
         [0., 0., 0., 2., 2., 2., 2., 2.],
         [0., 0., 0., 2., 2., 2., 2., 2.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 3., 3., 3., 3., 3.],
         [0., 0., 0., 3., 3., 3., 3., 3.],
         [0., 0., 0., 3., 3., 3., 3., 3.],
         [0., 0., 0., 3., 3., 3., 3., 3.],
       

In [37]:
x[None, :, None].shape

(1, 5, 1)

In [40]:
import torch

In [42]:
goo = torch.tensor([1,2,3,4,5])
goo

tensor([1, 2, 3, 4, 5])

In [44]:
goo[None, :, None].shape

torch.Size([1, 5, 1])

In [48]:
goo.view(1,5,1).expand(-1,-1,mask.sum())

NameError: name 'mask' is not defined